.Dd December 28, 2025
.Dt IAMANAWS 7
.Os 1.0.0
.Sh NAME
.Nm iamanaws
.Nd practical paranoid
.Sh DESCRIPTION
.Nm
believes in small tools, minimal trust, and systems that forget.
Developer by trade, paranoid by default.
.Sh SUPPORTED EXTENSIONS
*.nix, *.rs, *.ts, *.vue, *.tsx,
.br
*.py, *.php, *.go, *.sh, *.bash
.Sh ENVIRONMENT
.Ss PLATFORM
.Lk https://nixos.org NixOS ,
.Lk https://openbsd.org OpenBSD ,
.Lk https://9p.io/plan9/ "Plan 9" ,
.Lk https://alpinelinux.org alpinelinux
.Ss EDITOR
.Lk https://man.openbsd.org/tmux.1 tmux
+
.Lk https://man.archlinux.org/man/extra/neovim/nvim.1 neovim
.Ss PGP_KEY
.Lk https://keys.openpgp.org/vks/v1/by-fingerprint/CF10DCBB9318BE1D60404222272C61AB190DED28 "0x272C61AB190DED28"
.Sh CONTACT
.Lk mailto: iamanaws(α)httpd.dev
.Sh SEE ALSO
.Lk https://github.com/iamanaws github(4)
.\" .Sh COPYLEFT
.\" .An Angel J
.\" .Mt iamanaws(α)httpd.dev
.\" Copyleft (c) 2025, Angel J <iamanaws(α)httpd.dev>
.\" .br
.\" Released under copyleft terms. Share freely, modify responsibly.
