.Dd December 30, 2025
.Dt PARANOIA 7
.Os 1.0.0
.Sh NAME
.Nm paranoia
.Nd practical principles
.Sh DESCRIPTION
Constraints for a hostile world.
.Sh PRINCIPLES
.Ss ZERO-KNOWLEDGE
Blind data holds no truth
.Ss OFFLINE
The network is compromised.
.Ss COMPARTMENTALIZATION
Walls within walls.
.Ss EPHEMERAL
Ashes tell no tales.
.Sh BUGS
Humans are the weakest link.
.Sh SEE ALSO
.Lk https://ssd.eff.org ssd(7)

